# Generated by Django 4.0 on 2024-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0005_alter_temporaryfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
