# Generated by Django 4.0 on 2025-03-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter_app', '0006_alter_temporaryfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Outbox', 'Outbox'), ('Failed', 'Failed'), ('Sending', 'Sending'), ('Scheduled', 'Scheduled')], default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ManyToManyField(to='converter_app.EmailUsers')),
            ],
        ),
        migrations.DeleteModel(
            name='TemporaryFile',
        ),
    ]
